//! PTX (Parallel Thread Execution) text fact extraction.
//!
//! PTX modules are documented ASCII text beginning with a `.version` directive,
//! followed by `.target` and `.address_size` directives. cudabom reads only
//! these leading, documented directives to learn the ISA version, the SM
//! targets, and the address size. It scans a bounded prefix of the text so a
//! huge module does not cost more than the header is worth.
//!
//! Reference: the PTX ISA reference defines the `.version`, `.target`, and
//! `.address_size` directives and the `sm_NN` target naming.

use crate::facts::PtxFacts;

/// How many leading bytes of a PTX module to scan for directives. The header
/// directives appear at the very top; scanning a bounded prefix is sufficient
/// and cheap.
const SCAN_PREFIX: usize = 8 * 1024;

/// True if `bytes` looks like PTX text: printable and containing a `.version`
/// directive near the start.
#[must_use]
pub(crate) fn looks_like_ptx(bytes: &[u8]) -> bool {
    let prefix = &bytes[..bytes.len().min(SCAN_PREFIX)];
    // `from_utf8` already rejects most binary; then require the mandatory
    // `.version` directive at the start of a line.
    std::str::from_utf8(prefix).is_ok_and(has_version_directive)
}

/// Extract [`PtxFacts`] from PTX text. Returns `None` if it does not look like
/// PTX (no `.version` directive in the scanned prefix).
#[must_use]
pub(crate) fn parse(bytes: &[u8]) -> Option<PtxFacts> {
    let prefix = &bytes[..bytes.len().min(SCAN_PREFIX)];
    let text = std::str::from_utf8(prefix).ok()?;

    // Share the one definition of "is PTX" with `looks_like_ptx` so detection
    // and extraction cannot disagree on the same bytes.
    if !has_version_directive(text) {
        return None;
    }
    let isa_version = directive_value(text, ".version");
    let address_size =
        directive_value(text, ".address_size").and_then(|v| v.trim().parse::<u32>().ok());

    // Collect every `.target sm_NN` (a .target line may list multiple targets).
    let mut targets = Vec::new();
    for line in text.lines() {
        let line = line.trim_start();
        if let Some(rest) = line.strip_prefix(".target") {
            for token in rest.split([',', ' ', '\t']) {
                if let Some(num) = token.trim().strip_prefix("sm_") {
                    if let Ok(n) = num.parse::<u32>() {
                        targets.push(n);
                    }
                }
            }
        }
    }
    targets.sort_unstable();
    targets.dedup();

    Some(PtxFacts {
        isa_version,
        targets,
        address_size,
    })
}

/// True if any line in `text` begins (after leading whitespace) with the
/// `.version` directive, the mandatory first PTX directive.
fn has_version_directive(text: &str) -> bool {
    text.lines().any(|l| l.trim_start().starts_with(".version"))
}

/// Return the single-token value that follows `directive` on its line.
fn directive_value(text: &str, directive: &str) -> Option<String> {
    for line in text.lines() {
        let line = line.trim_start();
        if let Some(rest) = line.strip_prefix(directive) {
            let value = rest.trim();
            if !value.is_empty() {
                // Take the first whitespace-delimited token.
                return value.split_whitespace().next().map(ToString::to_string);
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "//\n// Generated by NVIDIA NVVM Compiler\n//\n\
        .version 8.3\n.target sm_90\n.address_size 64\n\n\
        .visible .entry _Z6kernelv() { ret; }\n";

    #[test]
    fn detects_ptx() {
        assert!(looks_like_ptx(SAMPLE.as_bytes()));
        assert!(!looks_like_ptx(b"\x7fELF not ptx"));
        assert!(!looks_like_ptx(b"just some text without the directive"));
    }

    #[test]
    fn parses_version_target_address_size() {
        let facts = parse(SAMPLE.as_bytes()).expect("ptx");
        assert_eq!(facts.isa_version.as_deref(), Some("8.3"));
        assert_eq!(facts.targets, vec![90]);
        assert_eq!(facts.address_size, Some(64));
    }

    #[test]
    fn parses_multiple_targets() {
        let text = ".version 7.5\n.target sm_70, sm_75, sm_80\n.address_size 64\n";
        let facts = parse(text.as_bytes()).unwrap();
        assert_eq!(facts.targets, vec![70, 75, 80]);
    }

    #[test]
    fn non_ptx_returns_none() {
        assert!(parse(b"\x00\x01\x02 binary").is_none());
    }
}
